name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check files (avoid hidden typos on CI)
        run: |
          python -V
          echo "----- app/exceptions.py -----"
          sed -n '1,120p' app/exceptions.py || true
          echo "----- app/calculator_config.py -----"
          sed -n '1,160p' app/calculator_config.py || true

      - name: Run tests with coverage (>=90%)
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov-fail-under=90
